name: 'Setup AKS Cluster using Terraform'

on:
  pull_request:
    branches:
    - develop
    paths:
    - 'aks-cluster/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Terraform initialization'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Terraform Init
      run: terraform -chdir=aks-cluster/ init
      # with:
      #   args: |
      #     -backend-config=storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
      #     -backend-config=container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
      #     -backend-config=key=${{ secrets.AZURE_STORAGE_KEY }}
      #     -backend-config=resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
      #     -backend-config=subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     -backend-config=tenant_id=${{ secrets.AZURE_TENANT_ID }}
      #     -backend-config=client_id=${{ secrets.AZURE_CLIENT_ID }}
      #     -backend-config=client_secret=${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Terraform Validate
      run: terraform -chdir=aks-cluster/ validate

    - name: Terraform Plan
      run: terraform -chdir=aks-cluster/ plan -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=aks-cluster/ apply "tfplan"
