name: 'Setup AKS Cluster using Terraform'

on:
  pull_request:
    branches:
    - develop
    paths:
    - 'aks-cluster/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Terraform initialization'
    runs-on: ubuntu-latest
    # environment: repo:Mbaoma/aks-cicd-with-terraform:ref:refs/heads/develop

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      # with:
      # creds: '${{ secrets.AZURE_CREDENTIALS }}'
      with:
        # client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Terraform Init
      run: terraform -chdir=aks-cluster/ init

    - name: Terraform Validate
      run: terraform -chdir=aks-cluster/ validate

    - name: Terraform Plan
      run: terraform -chdir=aks-cluster/ plan -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=aks-cluster/ apply "tfplan"
